import os
import sys

# 1. 🚀 PREVENT C++ ACCELERATION COLLISIONS
os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"   # Turn off conflicting oneDNN engine operations
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"     # Mute all heavy background framework logging

sys.modules['tensorflow'] = None

from pathlib import Path
import streamlit as st
import pandas as pd
import torch
from PIL import Image
# 🌟 Switched to tensorboardX to completely fix the web page freezing bug
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator

# --- Configure Page Style ---
st.set_page_config(page_title="Derma-CoSMO Workspace", page_icon="🩺", layout="wide")

# --- Define Paths from Your Updated Classification Script ---
DATA_DIR = Path("/home/s2522002/Experiment/prepared_data")
BALANCED_DIR = Path("/home/s2522002/Experiment/balanced_data")
RESULTS_DIR = Path("/home/s2522002/Experiment/Results")

# Generative & Validation metrics folder targets
GEN_IMG_DIR = Path("/home/s2522002/Experiment/Results/Sampled")
FID_DIR = Path("/home/s2522002/Experiment/Results/dermamnist_classifer/FID_Results")

# Define class mappings for DermaMNIST (7 classes)
CLASS_NAMES = {
    0: "Actinic keratoses (akiec)",
    1: "Basal cell carcinoma (bcc)",
    2: "Benign keratosis-like lesions (bkl)",
    3: "Dermatofibroma (df)",
    4: "Melanoma (mel)",
    5: "Melanocytic nevi (nv)",
    6: "Vascular lesions (vasc)"
}

# --- Application Header ---
st.title("🩺 Derma-CoSMO Framework")
st.markdown("### Latent-Space Generative Oversampling for Downstream Classification")
st.write("An end-to-end framework implementing joint contrastive alignment representation learning and algorithmic oversampling.")

# 🔄 Navigation Tabs
tab1, tab2, tab3 = st.tabs(["🖼️ Generative Gallery", "📊 Classification Performance", "🔬 Patient Diagnosis Inference"])

# =====================================================================
# TAB 1: GENERATIVE SYNTHESIS GALLERY
# =====================================================================
with tab1:
    st.subheader("Generative Representation Validation Gallery")
    
    # Render the saved FID Score CSV metrics directly onto card widgets
    fid_file = FID_DIR / "FID_Scores_sampled.csv"
    if fid_file.exists():
        st.markdown("#### 🎯 Distribution Quality Metrics (Lower is Better)")
        df_fid = pd.read_csv(fid_file)
        
        # Create columns to represent metrics beautifully
        cols = st.columns(len(df_fid))
        for index, row in df_fid.iterrows():
            c_idx = int(row['Class'])
            with cols[index]:
                st.metric(
                    label=f"Class {c_idx} ({CLASS_NAMES[c_idx].split()[-1]})", 
                    value=f"★ {row['Image_Feature_FID']:.2f}", 
                    delta=f"Latent: {row['Latent_FID']:.2f}",
                    delta_color="inverse"
                )
    
    st.markdown("---")
    st.markdown("#### 🖼️ Inspect Synthesized Images against Class Targets")
    selected_class_idx = st.selectbox(
        "Select Class Folder Target to View Decoded Output Samples:", 
        options=list(CLASS_NAMES.keys()), 
        format_func=lambda x: f"Class {x}: {CLASS_NAMES[x]}",
        key="sb_class_gallery"
    )
    
    target_class_dir = GEN_IMG_DIR / f"class_{selected_class_idx}"
    
    if target_class_dir.exists():
        img_files = [f for f in os.listdir(target_class_dir) if f.endswith('.png')]
        if img_files:
            st.write(f"Displaying synthetic samples generated by your trained Decoder model inside `{target_class_dir}`:")
            
            # Create a clean image layout grid row
            grid_cols = st.columns(5)
            for i, img_name in enumerate(img_files[:10]): # display up to 10 images safely
                col_target = grid_cols[i % 5]
                img_path = target_class_dir / img_name
                image = Image.open(img_path)
                col_target.image(image, caption=f"Synthetic Specimen #{i+1}", width='stretch')
        else:
            st.warning("No PNG files found in this class generation directory folder path yet.")
    else:
        st.info(f"Looking for model output plots inside your save directory. Run your generation script pipeline to populate files inside: `{target_class_dir}`")

# =====================================================================
# TAB 2: CLASSIFICATION PERFORMANCE DASHBOARD 
# =====================================================================
with tab2:
    st.subheader("Downstream Classifier Cross-Validation & Convergence Performance")
    
    col1, col2 = st.columns([1, 2])
    
    with col1:
        st.markdown("#### ⚙️ Architecture & Optimized Hyperparameters")
        
        # Architecture selectors - cleaned up quotes syntax from previous iteration
        selected_model = st.selectbox(
            "Target Classifier Architecture",
            ["resnet18", "efficientnet_b0", "mobilenet_v2", "vit", "vim"],
            key="sb_model_perf"
        )
        
        # Static Hyperparameter values for your path string construction
        lr_val = 0.0002
        latent_z = 64
        
        # Displaying them as elegant key-value badges
        h_col1, h_col2 = st.columns(2)
        with h_col1:
            st.metric(label="Optimal LR", value=f"{lr_val}")
        with h_col2:
            st.metric(label="Latent Space ($n\_z$)", value=f"{latent_z}")
        
        st.markdown("---")
        st.markdown("#### 📊 Selected Architecture Historical Metrics")
        results_file = RESULTS_DIR / "dermamnist_comprehensive_results.csv"
        
        if results_file.exists():
            df_results = pd.read_csv(results_file)
            df_model_all = df_results[df_results['Model'].str.lower() == selected_model.lower()]
            
            if not df_model_all.empty:
                df_summary = df_model_all[df_model_all['Fold'] == 'Average']
                df_folds = df_model_all[df_model_all['Fold'] != 'Average']
                
                st.markdown(f"**{selected_model.upper()} 5-Fold Summary Averages:**")
                st.dataframe(df_summary[['F1', 'ASCA', 'GM', 'AUC', 'ACC']], width='stretch')
                
                st.markdown(f"**{selected_model.upper()} Stability Across Folds:**")
                st.bar_chart(data=df_folds, x="Fold", y=["F1", "ACC", "AUC"])
            else:
                st.info(f"No logged matrix history found for {selected_model} in CSV files yet.")
        else:
            st.info("Awaiting baseline matrix logs to populate specific framework metrics.")

    with col2:
        st.markdown("#### 📈 Live Log Convergence Monitoring Studio")
        
        # 🌟 DYNAMIC PATH COMPOSITION
        tb_base_dir = Path("/home/s2522002/Experiment/Tensorboard")
        target_run_folder = tb_base_dir / f"{selected_model.lower()}_lr{lr_val}_z{latent_z}"
        
        st.info(f"📂 Target Log Directory: `{target_run_folder}`")
        
        if target_run_folder.exists():
            # Find the actual tfevents log file inside the folder target
            event_files = list(target_run_folder.glob("events.out.tfevents.*"))
            
            if event_files:
                target_event_file = event_files[0]
                
                # Pure-python memory safe TensorBoard parsing engine using tensorboardX
                try:
                    ea = EventAccumulator(str(target_event_file))
                    ea.Reload()
                    
                    # Automatically discover logged scalar tags (e.g., Loss, Accuracy curves)
                    scalar_tags = ea.Tags().get('scalars', [])
                    
                    if scalar_tags:
                        # 🌟 This selector will now load immediately and let you change graphs with zero lag!
                        selected_tag = st.selectbox(
                            "Select Scalar Tracking View (Acc / Loss Curves):", 
                            options=scalar_tags,
                            key="sb_tensorboard_tags"
                        )
                        
                        # Extract the metrics history steps and float values
                        scalar_data = ea.Scalars(selected_tag)
                        steps = [s.step for s in scalar_data]
                        values = [s.value for s in scalar_data]
                        
                        # Pack into a DataFrame and plot natively using Streamlit
                        chart_data = pd.DataFrame({
                            "Training Steps/Epochs": steps,
                            selected_tag: values
                        })
                        
                        st.line_chart(data=chart_data, x="Training Steps/Epochs", y=selected_tag)
                    else:
                        st.warning("The log file is initialized but no step metrics values have been written yet.")
                except Exception as e:
                    st.error(f"Error parsing log file: {e}")
            else:
                st.warning("Found run directory, but no matching `events.out.tfevents` record assets exist yet.")
        else:
            st.error("❌ Specified configuration target folder not found. Ensure this run path directory exists.")

# =====================================================================
# TAB 3: DOWNSTREAM PATIENT DIAGNOSIS INFERENCE (LIVE EVALUATION)
# =====================================================================
with tab3:
    st.subheader("Downstream Medical Diagnosis Assistant Pipeline")
    st.write("Upload a patient's raw dermatological dermoscopy image specimen (224 x 224) to perform live inference against your fine-tuned classification model ensemble.")
    
    # ── 🛠️ CACHED MODEL LOADING ENGINE ──
    @st.cache_resource
    def load_fine_tuned_resnet18():
        import torchvision.models as models
        import torch.nn as nn
        
        # 1. Rebuild identical architecture setup
        model = models.resnet18()
        model.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3, bias=False) # 3 RGB Channels
        model.fc = nn.Linear(model.fc.in_features, 7) # 7 DermaMNIST Output Targets
        
        # 2. Safely read weights file map location
        model_weights_path = "/home/s2522002/Experiment/Results/Saved_Models/resnet18_lr0.0002_z64.pth"
        
        if os.path.exists(model_weights_path):
            device = 'cuda' if torch.cuda.is_available() else 'cpu'
            state_dict = torch.load(model_weights_path, map_location=device)
            model.load_state_dict(state_dict)
            model = model.to(device)
            model.eval()
            return model, True
        else:
            return model, False

    # Initialize model check status
    classifier_model, weights_loaded_successfully = load_fine_tuned_resnet18()
    
    uploaded_file = st.file_uploader("Choose a dermoscopy patch image...", type=["jpg", "jpeg", "png"], key="file_uploader_diagnosis")
    
    if uploaded_file is not None:
        col1, col2 = st.columns(2)
        
        with col1:
            st.markdown("#### 📸 Uploaded Patient Asset")
            patient_img = Image.open(uploaded_file).convert("RGB") # Ensure standard 3-channel mode
            st.image(patient_img, caption="Target Scan Input", width=300)
            
        with col2:
            st.markdown("#### 🛡️ Framework Diagnostic Inference Predictive Probabilities")
            
            if not weights_loaded_successfully:
                st.error("❌ Pre-trained weights file not found at path: `/home/s2522002/Experiment/Results/Saved_Models/resnet18_lr0.0002_z64.pth`. Run your training script first to save the optimized model state.")
            else:
                with st.spinner("Executing model tensor graph logic..."):
                    from torchvision import transforms
                    import torch.nn.functional as F
                    
                    # 1. Apply exact DermaMNIST baseline evaluation transforms
                    inference_transforms = transforms.Compose([
                        transforms.Resize((224, 224)),
                        transforms.ToTensor(),
                        transforms.Normalize(
                            mean=[0.7630, 0.5456, 0.5700], 
                            std=[0.1409, 0.1526, 0.1699]
                        )
                    ])
                    
                    # 2. Format tensor dimensions for batch ingestion: [Batch, Channel, Height, Width]
                    input_tensor = inference_transforms(patient_img).unsqueeze(0)
                    device = 'cuda' if torch.cuda.is_available() else 'cpu'
                    input_tensor = input_tensor.to(device)
                    
                    # 3. Calculate actual forward pass probabilities
                    with torch.no_grad():
                        logits = classifier_model(input_tensor)
                        probabilities = F.softmax(logits, dim=1).squeeze(0).cpu().numpy()
                    
                    # 4. Map outputs safely to your global CLASS_NAMES dict
                    real_probabilities = {}
                    for class_idx, class_name in CLASS_NAMES.items():
                        real_probabilities[class_name] = float(probabilities[class_idx])
                    
                    # Pack metrics array for visualization component
                    df_prob = pd.DataFrame(
                        list(real_probabilities.items()), 
                        columns=['Diagnosis Target Class', 'Confidence Probability Score']
                    )
                    df_prob = df_prob.sort_values(by='Confidence Probability Score', ascending=True)
                    
                    # Render real interactive performance chart
                    st.bar_chart(data=df_prob, x="Diagnosis Target Class", y="Confidence Probability Score", horizontal=True)
                    
                    # 5. Highlight Top Prediction Target
                    top_match = df_prob.iloc[-1]
                    st.success(f"**Primary Automated Suggestion Match:** {top_match['Diagnosis Target Class']} ({top_match['Confidence Probability Score']*100:.1f}%)")